name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy over SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 10272
        script: |
          cd /srv/BeneluxCS
          git config pull.rebase true  # Prevents pull prompt
          git checkout main
          git pull --rebase origin main
          git lfs pull 
          sudo systemctl restart beneluxcs.service

